apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
    team: platform
    tier: client
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: curl
    image: curlimages/curl:8.10.1
    command: ["sleep","360000"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
