{
 "title": "Talos-Cilium-Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(source_namespace,label_values)"
    }
   },
   { "name": "node", "query": { "query": "label_values(up,node)" } },
   { "name": "pod", "query": { "query": "label_values(up,pod)" } },
   {
    "name": "envoy_pod",
    "query": {
     "query": "label_values(up{job=\"cilium-envoy\", namespace=\"kube-system\", container=\"cilium-envoy\"},pod)"
    }
   },
   {
    "name": "envoy_instance",
    "query": {
     "query": "label_values(up{job=\"cilium-envoy\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Falco Security Signals (Loki)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sidekick delivery failures/sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "failure/s" } },
   "targets": [
    {
     "expr": "sum by (destination) (rate(falcosecurity_falcosidekick_outputs_total{status!=\"ok\"}[5m])) or on() vector(0)\r\n",
     "legendFormat": "destination"
    },
    { "expression": "A", "reducer": "last", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Sidekick delivery failures/sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "failure/s" } },
   "targets": [
    {
     "expr": "sum(rate(falcosecurity_falcosidekick_outputs_total{status!=\"ok\"}[5m])) or vector(0)\r\n",
     "legendFormat": "falcosecurity-alerts"
    },
    { "expression": "A", "reducer": "last", "type": "reduce" },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "B",
     "type": "threshold"
    }
   ]
  },
  {
   "title": "Critical Events/sec (Falco → Loki)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "events/s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({priority=\"Critical\"}[5m])) or vector(0)\r\n",
     "legendFormat": "Critical Security Signals"
    }
   ]
  },
  {
   "title": "Critical Rules by hits (5m)",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (rule) (count_over_time({priority=\"Critical\"}[5m]))) or vector(0)\r\n"
    }
   ]
  },
  { "title": "BPF Map Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BPF map pressure — Top 10 (by node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, max by (node, map_name) (cilium_bpf_map_pressure))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BPF map pressure — Top 10 (cluster)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, max by (map_name) (cilium_bpf_map_pressure))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 Policy Evidence (HTTP “Envoy/L7 truth”)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "L7 Policy: Error Pressure: 2xx vs 3xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reg/s" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{\r\n  job=\"cilium-envoy\",\r\n  instance=~\"$envoy_instance\",\r\n  envoy_response_code_class=\"2\"\r\n}[1m])) or vector(0)\r\n",
     "legendFormat": "2xx = Success (e.g., 200 OK, 201 Created)"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{\r\n  job=\"cilium-envoy\",\r\n  instance=~\"$envoy_instance\",\r\n  envoy_response_code_class=\"3\"\r\n}[1m])) or vector(0)\r\n",
     "legendFormat": "3xx = Redirect (e.g., 301, 302, 304)"
    }
   ]
  },
  {
   "title": "L7 Policy: Error Pressure: 4xx vs 5xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(envoy_http_downstream_rq_xx{\r\n    job=\"cilium-envoy\",\r\n    instance=~\"$envoy_instance\",\r\n    envoy_response_code_class=\"4\"\r\n  }[1m])\r\n) or vector(0)\r\n",
     "legendFormat": "4xx = Client error (request rejected/invalid/unauthorized) (e.g., 401, 403, 404, 429)"
    },
    {
     "expr": "sum(\r\n  rate(envoy_http_downstream_rq_xx{\r\n    job=\"cilium-envoy\",\r\n    instance=~\"$envoy_instance\",\r\n    envoy_response_code_class=\"5\"\r\n  }[1m])\r\n) or vector(0)\r\n",
     "legendFormat": "5xx = Server error (service/envoy/upstream failed) (e.g., 500, 502, 503, 504)"
    }
   ]
  },
  {
   "title": "L7 Request Rate Cluster Wide (baseline traffic)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(envoy_http_downstream_rq_total{\r\n    job=\"cilium-envoy\",\r\n    instance=~\"$envoy_instance\"\r\n  }[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 Request Rate per_instance=$envoy_instance (baseline traffic)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(envoy_http_downstream_rq_total{\r\n    job=\"cilium-envoy\",\r\n    instance=~\"$envoy_instance\"\r\n  }[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 forwarded (sanity check)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_total{proxy_type=\"envoy\", rule=\"forwarded\"}[1m]))\r\n",
     "legendFormat": "confirm “deny happens while traffic exists”"
    }
   ]
  },
  {
   "title": "L7 deny Enforcement",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_total{proxy_type=\"envoy\", rule=\"denied\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 deny  Enforcement per-node=$node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (rate(cilium_policy_l7_total{proxy_type=\"envoy\", rule=\"denied\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latency p95 selected ns=$namespace",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(envoy_http_downstream_rq_time_bucket{job=\"cilium-envoy\", pod=~\"$envoy_pod\"}[5m])))\r\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(envoy_http_downstream_rq_time_bucket{job=\"cilium-envoy\", pod=~\"$envoy_pod\"}[5m])))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(envoy_http_downstream_rq_time_bucket{job=\"cilium-envoy\", pod=~\"$envoy_pod\"}[5m])))\r\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "HTTP requests/sec (cluster)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{job=\"cilium-envoy\"}[5m]))\r\n",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "HTTP requests/sec by Envoy pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(envoy_http_downstream_rq_total{job=\"cilium-envoy\", pod=~\"$envoy_pod\"}[1m])\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hubble telementry health (lost events) - 0=OK, 1=DEGRADED",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "max_over_time((sum(rate(hubble_lost_events_total{job=\"hubble-metrics\"}[5m])))[10m:]) > 0\r\n",
     "legendFormat": "<1 and >=1"
    }
   ]
  },
  {
   "title": "Lost events table (node + pod + value)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "topk(\r\n  20,\r\n  sum by (node, pod, instance) (\r\n    increase(hubble_lost_events_total{job=\"hubble-metrics\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Policy Evidence (L3/L4 \"Kernel Datapath truth\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Cilium components UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"cilium-agent\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium targets up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"cilium-agent\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Agent UP %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(up{job=\"cilium-agent\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hubble Metrics UP %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(up{job=\"hubble-metrics\"})\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium Operator UP %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(up{job=\"cilium-operator\"})\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top drop reasons (datapath)",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 56 },
   "targets": [
    {
     "expr": "topk(10, sum by (reason) (rate(cilium_drop_count_total{reason!=\"\"}[5m])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy denied drops/sec (cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "drop/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium drops/sec by node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(cilium_drop_count_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node + src ns + dst ns + reason + drops/sec (truth table)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "topk(\r\n  50,\r\n  sum by (node, source_namespace, reason) (\r\n    label_replace(\r\n      label_replace(\r\n        rate(hubble_drop_total{job=\"hubble-metrics\"}[5m]),\r\n        \"destination_namespace\", \"unknown\",\r\n        \"destination_namespace\", \"^$\"\r\n      ),\r\n      \"source_namespace\", \"host\",\r\n      \"source_namespace\", \"^$\"\r\n    )\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top source namespaces by flows (Hubble)",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  sum by (source_namespace) (\r\n    label_replace(\r\n      rate(hubble_flows_processed_total{job=\"hubble-metrics\"}[5m]),\r\n      \"source_namespace\",\"host\",\"source_namespace\",\"^$\"\r\n    )\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top destination namespaces by flows (Hubble)",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "topk(\r\n  20,\r\n  sum by (destination_namespace) (\r\n    rate(hubble_flows_processed_total{job=\"hubble-metrics\", destination_namespace!=\"\"}[5m])\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop ratio (%)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  100 *\r\n  (\r\n    sum by (source_namespace) (\r\n      label_replace(\r\n        rate(hubble_drop_total{job=\"hubble-metrics\"}[5m]),\r\n        \"source_namespace\",\"host\",\"source_namespace\",\"^$\"\r\n      )\r\n    )\r\n  )\r\n  /\r\n  clamp_min(\r\n    sum by (source_namespace) (\r\n      label_replace(\r\n        rate(hubble_flows_processed_total{job=\"hubble-metrics\"}[5m]),\r\n        \"source_namespace\",\"host\",\"source_namespace\",\"^$\"\r\n      )\r\n    ),\r\n    1e-9\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drop ratio (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum by (source_namespace) (rate(hubble_drop_total{job=\"hubble-metrics\", source_namespace!=\"\"}[5m])))\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Namespaces by Drop (Hubble)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (source_namespace) (\r\n    label_replace(\r\n      rate(hubble_drop_total{job=\"hubble-metrics\"}[5m]),\r\n      \"source_namespace\",\"host\",\"source_namespace\",\"^$\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Namspaces by Drop (Hubble)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "drop/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (source_namespace) (\r\n    label_replace(\r\n      rate(hubble_drop_total{job=\"hubble-metrics\"}[5m]),\r\n      \"source_namespace\",\"host\",\"source_namespace\",\"^$\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Namespaces by Flows (Hubble)",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  sum by (source_namespace) (\r\n    rate(hubble_flows_processed_total{job=\"hubble-metrics\", source_namespace!=\"\"}[5m])\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Namespaces by Flows (Hubble)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "flow/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  sum by (source_namespace) (\r\n    rate(hubble_flows_processed_total{job=\"hubble-metrics\", source_namespace!=\"\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cilium/Hubble Signals by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Top Nodes By Flow",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by (node) (\r\n  rate(hubble_flows_processed_total{job=\"hubble-metrics\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Nodes By Drop",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum by (node) (\r\n  rate(hubble_drop_total{job=\"hubble-metrics\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node-level network health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Flows/sec by node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops/sec" } },
   "targets": [
    {
     "expr": "sum by (node) (\r\n  rate(hubble_flows_processed_total{job=\"hubble-metrics\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drops/sec by node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops/sec" } },
   "targets": [
    {
     "expr": "sum by (node) (\r\n  rate(hubble_drop_total{job=\"hubble-metrics\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic (high level)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Hubble flows/sec (cluster)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{job=\"hubble-metrics\"}[5m]))\r\n",
     "legendFormat": "Flows processed (flows/s)"
    }
   ]
  },
  {
   "title": "Hubble drops/sec (cluster)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ops/sec" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{job=\"hubble-metrics\"}[5m]))\r\n",
     "legendFormat": "Drops processed (drops/s)"
    }
   ]
  },
  {
   "title": "Prometheus Scrap health (min up) - 1=OK, 0=Down",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "min(up{job=~\"hubble-metrics|cilium-agent|cilium-operator\"})\r\n",
     "legendFormat": "min up"
    }
   ]
  }
 ]
}